FROM python:3.10-slim

RUN apt update && apt install -y ffmpeg mkvtoolnix rclone git

RUN pip install --upgrade pip
RUN pip install torch torchvision torchaudio
RUN pip install faster-whisper yt-dlp

WORKDIR /app
COPY . /app

CMD ["bash"]
